# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/socrates/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),socrates)

$(call add-radio-file-sha1-checked,radio/abl.img,e71a586532b87e5ad60bbfc601d17154de408a07)
$(call add-radio-file-sha1-checked,radio/aop.img,e7a409be9749ffbb806669d97d83fc4a9b155402)
$(call add-radio-file-sha1-checked,radio/aop_config.img,56f6175dc773b218480881a20c7fd981fce7a492)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,754fb772958ea671909146cb93ccedec4d1ca977)
$(call add-radio-file-sha1-checked,radio/cpucp.img,a31534978327105d7d1bb03c461fdd9ffff30d9c)
$(call add-radio-file-sha1-checked,radio/devcfg.img,1b118ff5e011db29c2ba45699feb0316ec200eb1)
$(call add-radio-file-sha1-checked,radio/dsp.img,e9cde04e0b0842e4be578f17944a8950b4a04ad3)
$(call add-radio-file-sha1-checked,radio/featenabler.img,fdda2180c2c85527ccc412aa3d6f0798e54ade2b)
$(call add-radio-file-sha1-checked,radio/hyp.img,5ad059ef421603093db070989d472e9d729a47cc)
$(call add-radio-file-sha1-checked,radio/imagefv.img,6a0225b719c8e49a1cef41f8b12b60d49b67d5fa)
$(call add-radio-file-sha1-checked,radio/keymaster.img,4a765cc455e80b03e8d639c98561d3a9f1aea9c5)
$(call add-radio-file-sha1-checked,radio/modem.img,767af5043ecba9252c47db8374e7ba3e10f3ebfe)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0ec5dc9f9b826928fc55aa320c5241373c045ec7)
$(call add-radio-file-sha1-checked,radio/shrm.img,ab5946e55d154522ead509fbeee7a7305ea5b201)
$(call add-radio-file-sha1-checked,radio/tz.img,7604b919385eeebde7cee29c682a6f90859cf3c9)
$(call add-radio-file-sha1-checked,radio/uefi.img,10951eafdb2a62e6f56c50c6dadcbf98b8e092b1)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,062fd91b5581ca38de4ec70cfccb605c17792832)
$(call add-radio-file-sha1-checked,radio/xbl.img,2cd64ee302c8bab7f9631cc99c587acaebc61a22)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,d90e84eed1b7bc8daf7e354531b82dd65dd8bed2)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,3c3bfed4dd25deac52475183e53d3aa53b350ea2)

endif
