#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/socrates

PRODUCT_COPY_FILES += \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/CFR_para_UW_V01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_UW_V01.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/CFR_para_UW_V01_HD.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_UW_V01_HD.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/CFR_para_UW_V01_HDR.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_UW_V01_HDR.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/CFR_para_UW_V01_SN.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CFR_para_UW_V01_SN.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_ODM)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/MobNetv2TF_0.35_iter200000_zoom2.5x_h1500w2000.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/MobNetv2TF_0.35_iter200000_zoom2.5x_h1500w2000.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/altekldc_packdata_0x01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/altekldc_packdata_0x01.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/altekldc_segmodel.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/altekldc_segmodel.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/altekldc_tuningdata.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/altekldc_tuningdata.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/altekldc_tuningdata_ai.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/altekldc_tuningdata_ai.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/anc_1080p.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/anc_1080p.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/anc_4k.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/anc_4k.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/arcsat_2sat.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/arcsat_2sat.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/arcsoft_dynamicEV_config.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/arcsoft_dynamicEV_config.ini \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/beauty_config_cn.json:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_config_cn.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/beauty_config_gl.json:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_config_gl.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/beauty_style_nude.cng:$(TARGET_COPY_OUT_ODM)/etc/camera/beauty_style_nude.cng \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/bokehParams.json:$(TARGET_COPY_OUT_ODM)/etc/camera/bokehParams.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/camerabooster.json:$(TARGET_COPY_OUT_ODM)/etc/camera/camerabooster.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/com.xiaomi.dcal.wu.data:$(TARGET_COPY_OUT_ODM)/etc/camera/com.xiaomi.dcal.wu.data \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/com.xiaomi.dcal.wu.golden:$(TARGET_COPY_OUT_ODM)/etc/camera/com.xiaomi.dcal.wu.golden \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/denoise_qat.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/denoise_qat.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/dualcam_bokeh_params_pro_front.json:$(TARGET_COPY_OUT_ODM)/etc/camera/dualcam_bokeh_params_pro_front.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/eisoverridesettings.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/eisoverridesettings.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/enhance_motiontuning.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/enhance_motiontuning.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/detlmk.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/detlmk.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/facedet_dark_full.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_dark_full.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/facedet_dark_part.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_dark_part.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/facedet_front.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_front.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/facedet_full.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_full.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/facedet_part.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facedet_part.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/facefocus_models/facevalid.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/facefocus_models/facevalid.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/hdrcheckerextendparamsettings.yml:$(TARGET_COPY_OUT_ODM)/etc/camera/hdrcheckerextendparamsettings.yml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/hdrcheckerparamsettings.yml:$(TARGET_COPY_OUT_ODM)/etc/camera/hdrcheckerparamsettings.yml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/his_gme_wide.yaml:$(TARGET_COPY_OUT_ODM)/etc/camera/his_gme_wide.yaml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/his_preview_wide.yaml:$(TARGET_COPY_OUT_ODM)/etc/camera/his_preview_wide.yaml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/his_video_wide.yaml:$(TARGET_COPY_OUT_ODM)/etc/camera/his_video_wide.yaml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/mage_yuv_hdr_opencl.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mage_yuv_hdr_opencl.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/mi_tuning/default.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mi_tuning/default.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/mi_tuning/socrates_semco_imx800_wide.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/mi_tuning/socrates_semco_imx800_wide.bin \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/miai_hdr_config.yaml:$(TARGET_COPY_OUT_ODM)/etc/camera/miai_hdr_config.yaml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/miai_psn_config.yaml:$(TARGET_COPY_OUT_ODM)/etc/camera/miai_psn_config.yaml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/mihal_overlap/overlap_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/mihal_overlap/overlap_config.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/mihal_overlap/proj_overlap_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/mihal_overlap/proj_overlap_config.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/misoverridesettings.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/misoverridesettings.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_ai_dxo.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_ai_dxo.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_aiie_cap.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_aiie_cap.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_back.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_front.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_front_mibokeh_video.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_front_mibokeh_video.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_glass.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_glass.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/model_indoor.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/model_indoor.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/motiontuning.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/motiontuning.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/night_motiontuning.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/night_motiontuning.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/ocr_aio:$(TARGET_COPY_OUT_ODM)/etc/camera/ocr_aio \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/portrait_segmentation_qat.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/portrait_segmentation_qat.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/portraitrepaire_front_class.json:$(TARGET_COPY_OUT_ODM)/etc/camera/portraitrepaire_front_class.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/portraitrepaire_front_live.json:$(TARGET_COPY_OUT_ODM)/etc/camera/portraitrepaire_front_live.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/portraitrepaire_rear_class.json:$(TARGET_COPY_OUT_ODM)/etc/camera/portraitrepaire_rear_class.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/portraitrepaire_rear_live.json:$(TARGET_COPY_OUT_ODM)/etc/camera/portraitrepaire_rear_live.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/preview_bokeh_params_mono.json:$(TARGET_COPY_OUT_ODM)/etc/camera/preview_bokeh_params_mono.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/sky_segmentation_qat.dlc:$(TARGET_COPY_OUT_ODM)/etc/camera/sky_segmentation_qat.dlc \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/snsc_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/snsc_params.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/svq_cache:$(TARGET_COPY_OUT_ODM)/etc/camera/svq_cache \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_ODM)/etc/camera/vidhance_calibration \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/EcoCloudInfo.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/EcoCloudInfo.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/dualbokehjpegsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/dualbokehjpegsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/dualbokehsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/dualbokehsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/ecovendorstreamconfig.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/ecovendorstreamconfig.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/frontbokehsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontbokehsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/frontsinglesnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontsinglesnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/frontsupernightsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontsupernightsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/frontsupernightsnapshotjpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/frontsupernightsnapshotjpeg.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/manualsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/manualsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/miuicamerayuv2heic.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/miuicamerayuv2heic.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/miuicamerayuv2jpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/miuicamerayuv2jpeg.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/mivisettings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/mivisettings.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/mivistreamformat.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/mivistreamformat.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/mivivendorstreamconfig.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/mivivendorstreamconfig.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/normalsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/normalsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/overridesettings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/overridesettings.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/rearsupernightsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/rearsupernightsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/satburstsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satburstsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/satsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/satsnapshotjpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/satsnapshotjpeg.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/settings.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/settings.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/superhdsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/superhdsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/thirdpartydualbokehyuvsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdpartydualbokehyuvsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/thirdpartyjpegsnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdpartyjpegsnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/thirdpartyrawsupernightjpeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdpartyrawsupernightjpeg.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/thirdpartyrawsupernightyuv.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdpartyrawsupernightyuv.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomi/thirdpartysnapshot.json:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/thirdpartysnapshot.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/camera/xiaomiSceneDetection.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomiSceneDetection.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/df_default.xml:$(TARGET_COPY_OUT_ODM)/etc/df_default.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLutInfo.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLutInfo.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_0.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_0.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_1.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_1.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_10.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_10.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_11.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_11.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_12.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_12.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_13.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_13.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_14.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_14.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_15.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_15.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_16.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_16.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_17.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_17.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_18.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_18.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_19.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_19.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_2.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_2.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_20.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_20.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_3.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_3.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_4.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_4.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_5.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_5.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_6.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_6.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_7.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_7.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_8.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_8.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_9.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/miLut_9.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_0.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_0.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_1.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_1.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_2.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_2.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_3.txt:$(TARGET_COPY_OUT_ODM)/etc/disp0/mdss_dsi_m11_42_02_0a_dsc_cmd/mi_gc_3.txt \
    vendor/xiaomi/socrates/proprietary/odm/etc/display/qdcm_calib_data_xiaomi_42_02_0a_cmd_mode_dsc_dsi_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_xiaomi_42_02_0a_cmd_mode_dsc_dsi_panel.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_ODM)/etc/dolby/dax-default.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/dolby_vision.cfg:$(TARGET_COPY_OUT_ODM)/etc/dolby_vision.cfg \
    vendor/xiaomi/socrates/proprietary/odm/etc/init/vendor.qti.camera.provider-service_64.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.qti.camera.provider-service_64.rc \
    vendor/xiaomi/socrates/proprietary/odm/etc/mdss_dsi_m11_42_02_0a_dsc_cmd_mi.xml:$(TARGET_COPY_OUT_ODM)/etc/mdss_dsi_m11_42_02_0a_dsc_cmd_mi.xml \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/kailua_qsh_ble_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/kailua_qsh_ble_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/lsm6dso_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/qmc6308_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qmc6308_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_ble.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/qsh_camera.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_camera.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_default_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_default_sensors.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_dynamic_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_dynamic_sensors.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_irq.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_irq.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_lsm6dso_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_lsm6dso_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_power_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_power_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_qmc6308_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_qmc6308_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_stk3bcx_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_stk3bcx_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_sx933x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_sx933x_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sm8550_tsl2522_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8550_tsl2522_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_aod.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_ccd_v5.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v5.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_dbtap.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_dbtap.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_hand_detect.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_hand_detect.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_nonui.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_nonui.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_oem13.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_oem13.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_oem_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_oem_pocket.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_sar_algo.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_sar_algo.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_sar_algo_1.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_sar_algo_1.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_screen_down.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_screen_down.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/stk3bcx_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/stk3bcx_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/sensors/config/sx933x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sx933x_0.json \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-4k.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-4k.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-arvr.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-camera.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-camera.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-cclassvideo.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-cclassvideo.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-cgame.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-cgame.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-chg-only.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-class0.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-class0.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-cmgame.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-cmgame.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-cyuanshen.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-cyuanshen.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-dolbyvision.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-dolbyvision.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-huanji.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-huanji.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-mgame.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-navigation.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-nolimits.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-normal.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-normal.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-per-cclassvideo.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-per-cclassvideo.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-per-cgame.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-per-cgame.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-per-class0.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-per-class0.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-per-normal.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-per-normal.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-per-video.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-per-video.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-phone.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-phone.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-tgame.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-video.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-video.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-videochat.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-videochat.conf \
    vendor/xiaomi/socrates/proprietary/odm/etc/thermal-yuanshen.conf:$(TARGET_COPY_OUT_ODM)/etc/thermal-yuanshen.conf \
    vendor/xiaomi/socrates/proprietary/odm/firmware/B-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_ODM)/firmware/B-cs35l41-dsp1-spk-cali.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/B-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_ODM)/firmware/B-cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/B-handfree.txt:$(TARGET_COPY_OUT_ODM)/firmware/B-handfree.txt \
    vendor/xiaomi/socrates/proprietary/odm/firmware/B-music.txt:$(TARGET_COPY_OUT_ODM)/firmware/B-music.txt \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b00 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b01 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b02 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b03 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b04 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b05 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b06 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b07 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b08 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b09 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b10 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b11 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b12 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b13 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b14 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b15 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b16 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b17 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b18 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b19 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b20 \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.elf \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mbn \
    vendor/xiaomi/socrates/proprietary/odm/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mdt \
    vendor/xiaomi/socrates/proprietary/odm/firmware/T-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_ODM)/firmware/T-cs35l41-dsp1-spk-cali.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/T-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_ODM)/firmware/T-cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/T-handfree.txt:$(TARGET_COPY_OUT_ODM)/firmware/T-handfree.txt \
    vendor/xiaomi/socrates/proprietary/odm/firmware/T-handset.txt:$(TARGET_COPY_OUT_ODM)/firmware/T-handset.txt \
    vendor/xiaomi/socrates/proprietary/odm/firmware/T-music.txt:$(TARGET_COPY_OUT_ODM)/firmware/T-music.txt \
    vendor/xiaomi/socrates/proprietary/odm/firmware/cs35l41-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_ODM)/firmware/cs35l41-dsp1-spk-cali.wmfw \
    vendor/xiaomi/socrates/proprietary/odm/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_ODM)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_cfg_group_m11.bin:$(TARGET_COPY_OUT_ODM)/firmware/goodix_cfg_group_m11.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_cfg_group_m11_new.bin:$(TARGET_COPY_OUT_ODM)/firmware/goodix_cfg_group_m11_new.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_firmware_m11.bin:$(TARGET_COPY_OUT_ODM)/firmware/goodix_firmware_m11.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_firmware_m11_new.bin:$(TARGET_COPY_OUT_ODM)/firmware/goodix_firmware_m11_new.bin \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_normalize.csv:$(TARGET_COPY_OUT_ODM)/firmware/goodix_normalize.csv \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_normalize_1.csv:$(TARGET_COPY_OUT_ODM)/firmware/goodix_normalize_1.csv \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_test_limits_1_255.csv:$(TARGET_COPY_OUT_ODM)/firmware/goodix_test_limits_1_255.csv \
    vendor/xiaomi/socrates/proprietary/odm/firmware/goodix_test_limits_255.csv:$(TARGET_COPY_OUT_ODM)/firmware/goodix_test_limits_255.csv \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.qti_tpg0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.qti_tpg0.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.qti_tpg1.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.qti_tpg1.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.qti_tpg2.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.qti_tpg2.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.socrates_ofilm_ov08d10_ultra.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.socrates_ofilm_ov08d10_ultra.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.socrates_ofilm_ov16a1q_front.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.socrates_ofilm_ov16a1q_front.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.socrates_semco_imx800_wide.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.socrates_semco_imx800_wide.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.sensormodule.socrates_sunny_ov02b10_macro.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.socrates_sunny_ov02b10_macro.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.tuned.socrates_ofilm_ov08d10_ultra.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.socrates_ofilm_ov08d10_ultra.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.tuned.socrates_ofilm_ov16a1q_front.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.socrates_ofilm_ov16a1q_front.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.tuned.socrates_semco_imx800_wide.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.socrates_semco_imx800_wide.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.tuned.socrates_sunny_ov02b10_macro.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.socrates_sunny_ov02b10_macro.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/com.qti.tuned.tpg.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.tpg.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigpreview.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigvideo.bin \
    vendor/xiaomi/socrates/proprietary/odm/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigvideolite.bin \
    vendor/xiaomi/socrates/proprietary/vendor/etc/acdbdata/kalama_mtp/Tutu_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_mtp/Tutu_acdb_cal.acdb \
    vendor/xiaomi/socrates/proprietary/vendor/etc/acdbdata/kalama_mtp/Tutu_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_mtp/Tutu_workspaceFileXml.qwsp \
    vendor/xiaomi/socrates/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/xiaomi/socrates/proprietary/vendor/etc/df_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/df_default.xml \
    vendor/xiaomi/socrates/proprietary/vendor/etc/display/3dlut-pt-onnx-ptq-htp-fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/3dlut-pt-onnx-ptq-htp-fp16.dlc \
    vendor/xiaomi/socrates/proprietary/vendor/etc/displayconfig/display_id_4630946545580055171.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630946545580055171.xml \
    vendor/xiaomi/socrates/proprietary/vendor/etc/displayconfig/display_layout_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_layout_configuration.xml \
    vendor/xiaomi/socrates/proprietary/vendor/etc/qvr/cfg/519/0/65536/mtpkailua.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/519/0/65536/mtpkailua.txt \
    vendor/xiaomi/socrates/proprietary/vendor/etc/qvr/cfg/519/0/65536/mtpkailua_6dof_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/519/0/65536/mtpkailua_6dof_config.xml \
    vendor/xiaomi/socrates/proprietary/vendor/etc/qvr/cfg/519/0/65536/mtpkailua_qvr_3dof_tracker_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/cfg/519/0/65536/mtpkailua_qvr_3dof_tracker_config.txt \
    vendor/xiaomi/socrates/proprietary/vendor/etc/qvr/qvr_hid_device_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/qvr_hid_device_list.txt \
    vendor/xiaomi/socrates/proprietary/vendor/etc/qvr/qvr_usb_device_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/qvr_usb_device_list.txt \
    vendor/xiaomi/socrates/proprietary/vendor/etc/qvr/qvrservice_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qvr/qvrservice_config.txt \
    vendor/xiaomi/socrates/proprietary/vendor/etc/sensors/config/chre_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/chre_dynamic_sensors.json \
    vendor/xiaomi/socrates/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/socrates/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/xiaomi/socrates/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/socrates/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/socrates/proprietary/vendor/etc/vibrator/effect_0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_0.bin \
    vendor/xiaomi/socrates/proprietary/vendor/etc/vibrator/effect_1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_1.bin \
    vendor/xiaomi/socrates/proprietary/vendor/etc/vibrator/effect_2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_2.bin \
    vendor/xiaomi/socrates/proprietary/vendor/etc/vibrator/effect_3.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_3.bin \
    vendor/xiaomi/socrates/proprietary/vendor/etc/vibrator/effect_4.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_4.bin \
    vendor/xiaomi/socrates/proprietary/vendor/etc/vibrator/effect_5.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_5.bin

PRODUCT_PACKAGES += \
    libPlatformValidatorShared-camera \
    libPlatformValidatorShared \
    libQnnChrometraceProfilingReader \
    libQnnGpu \
    libQnnGpuNetRunExtensions \
    libQnnGpuProfilingReader \
    libQnnHtpNetRunExtensions \
    libQnnHtpProfilingReader \
    libQnnHtpV73CalculatorStub \
    libQnnSaver \
    libSNPE \
    libSNPESample \
    libScenescape \
    libSnpeDspV65Stub \
    libSnpeDspV66Stub \
    libSnpeHta \
    libSnpeHtpPrepare \
    libSnpeHtpV68Stub \
    libSnpeHtpV69Stub \
    libSnpeHtpV73Stub \
    libStereoRectifyWrapper \
    libbitmlenginev2 \
    libcalculator \
    libcalculator_htp \
    libcamxexternalformatutils \
    libos \
    libqvr_cam_cdsp_driver_stub \
    libqvr_cdsp_driver_stub \
    libqvrcamera_client.qti \
    libqvrcameraplayback \
    libqvrservice_client.qti \
    libqvrservice_ov7251_hvx_tuning \
    libqvrservice_ov9282_hvx_tuning \
    libqvrservice_v4l_ov7251_hvx_tuning \
    libsynx \
    libthreadutils \
    vendor.qti.hardware.qxr-V1-ndk \
    vendor.xiaomi.hardware.bgservice@1.0 \
    vendor_lib_rfsa_adsp_capi_cirrus_sp_so \
    vendor_lib_rfsa_adsp_chre_qsh_shim_so \
    vendor_lib_rfsa_adsp_libCalculator_skel_so \
    vendor_lib_rfsa_adsp_libDspIOProxy_skel_so \
    vendor_lib_rfsa_adsp_libQ6MSFR_manager_skel_so \
    vendor_lib_rfsa_adsp_libQnnHtpV73_so \
    vendor_lib_rfsa_adsp_libQnnHtpV73Skel_so \
    vendor_lib_rfsa_adsp_libQnnSaver_so \
    vendor_lib_rfsa_adsp_libSnpeDspV65Skel_so \
    vendor_lib_rfsa_adsp_libSnpeDspV66Skel_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV68Skel_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV69Skel_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV73Skel_so \
    vendor_lib_rfsa_adsp_libVppAisQnnHtp_so \
    vendor_lib_rfsa_adsp_libVppFrcQnnHtp_so \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapn_dsp_skel_so \
    vendor_lib_rfsa_adsp_libarc_htp_driver_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_v2_skel_so \
    vendor_lib_rfsa_adsp_libcalculator_skel_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_qvrcam_receiver_so \
    vendor_lib_rfsa_adsp_libevadsp_3_0_so \
    vendor_lib_rfsa_adsp_libeye_tracking_dsp_sample_skel_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhalide_hexagon_remote_skel_so \
    vendor_lib_rfsa_adsp_libhdr_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libhdr_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_basic_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_ldc_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_mc_bokeh_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_rawhdr_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_rfs_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_slow_motion_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_networks_so \
    vendor_lib_rfsa_adsp_libqvr_3dof_tracker_skel_so \
    vendor_lib_rfsa_adsp_libqvr_cam_dsp_driver_skel_so \
    vendor_lib_rfsa_adsp_libqvr_dsp_driver_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libtracker_6dof_skel_8450_so \
    vendor_lib_rfsa_adsp_libvpp_ais_so \
    vendor_lib_rfsa_adsp_libvpp_ais_networks_so \
    vendor_lib_rfsa_adsp_libvpp_frc_so \
    vendor_lib_rfsa_adsp_libvpp_svc_skel_so \
    vendor_lib_rfsa_adsp_libvpp_vqa_networks_so \
    vendor_lib_rfsa_adsp_nearby_napp_header \
    vendor_lib_rfsa_adsp_nearby_so \
    com.qti.actuator.socrates_semco_imx800_dw9825a_wide_actuator \
    com.qti.eeprom.socrates_ofilm_ov08d10_p24c64f_ultra_eeprom \
    com.qti.eeprom.socrates_ofilm_ov16a1q_gt24p64e_front_eeprom \
    com.qti.eeprom.socrates_semco_imx800_p24c256f_wide_eeprom \
    com.qti.eeprom.socrates_sunny_ov02b10_gt24p64e_macro_eeprom \
    com.qti.sensor.socrates_ofilm_ov08d10_ultra \
    com.qti.sensor.socrates_ofilm_ov16a1q_front \
    com.qti.sensor.socrates_semco_imx800_wide \
    com.qti.sensor.socrates_sunny_ov02b10_macro \
    com.bots.node.vendortagwrite \
    com.mi.node.aiasd \
    com.mi.node.dlengine \
    com.mi.node.eisv2 \
    com.mi.node.facealign \
    com.mi.node.frontbokeh \
    com.mi.node.hdr \
    com.mi.node.mawcommon \
    com.mi.node.mawsaliency \
    com.mi.node.mimovie \
    com.mi.node.realtimebokeh \
    com.mi.node.rearvideo \
    com.mi.node.skinbeautifier \
    com.mi.node.tsskinbeautifier \
    com.mi.node.videobokeh \
    com.mi.node.videofilter \
    com.mi.node.videonight \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.hdr10plushist \
    com.qti.node.hdr10plusmeta \
    com.qti.node.ldc \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.muxer \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.xiaomi.node.gme \
    com.xiaomi.node.misv2 \
    com.xiaomi.node.misv3 \
    com.xiaomi.node.smooth_transition \
    com.xiaomi.stats.af \
    com.xiaomi.stats.pdlib \
    libdepthmapwrapper_secure \
    libstats.afalgo \
    libstats.pdlib \
    libchxlogicalcameratable \
    com.xiaomi.plugin.anchor \
    com.xiaomi.plugin.arcsofthdr \
    com.xiaomi.plugin.arcsoftsll \
    com.xiaomi.plugin.capbokeh \
    com.xiaomi.plugin.capdepth \
    com.xiaomi.plugin.caphdr \
    com.xiaomi.plugin.depurple \
    com.xiaomi.plugin.frontbokeh \
    com.xiaomi.plugin.gpu \
    com.xiaomi.plugin.hdr \
    com.xiaomi.plugin.ldc \
    com.xiaomi.plugin.memcpy \
    com.xiaomi.plugin.miaideblur \
    com.xiaomi.plugin.miaiie \
    com.xiaomi.plugin.miaiportraitsupernight \
    com.xiaomi.plugin.mialgosnsc \
    com.xiaomi.plugin.offlinepostproc \
    com.xiaomi.plugin.portraitrepair \
    com.xiaomi.plugin.skinbeautifier \
    com.xiaomi.plugin.sr \
    camx.device-impl \
    camx.provider-impl \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.ellcprocess \
    com.qti.feature2.ellcsupernight \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8550 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.offlinestatsregeneration \
    com.qti.feature2.qcfa \
    com.qti.feature2.qllimagedump \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rawsupernight \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8550 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    com.qualcomm.qti.mcx.usecase.extension \
    com.xiaomi.camhal.overlap \
    com.xiaomi.camhal.submodel.camxfrag \
    com.xiaomi.camhal.submodel.chifrag \
    camera.qcom \
    camera.xiaomi \
    com.qti.chi.offline \
    com.qti.chi.override \
    fingerprint.goodix_fod.default \
    libAF \
    libHISCppAlgos \
    libMiMotion \
    libMiVideoFilter \
    libTrueSight \
    libXMFaceFocus \
    libaachaptics \
    libaidenoiser \
    libaidenoiserv2 \
    libalAILDC \
    libalAI_Seg \
    libalCFR \
    libalLDC \
    libalNN \
    libalNN_engine \
    libalNN_gpu \
    libalNN_snpe \
    libanc_supervq \
    libarc_sat \
    libarc_translate \
    libarccali_data \
    libarcsoft_beautyshot \
    libarcsoft_bokeh_high_dynamic_range \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_post \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_mf_superresolution \
    libarcsoft_qnnhtp \
    libarcsoft_super_night_detection \
    libarcsoft_super_night_raw \
    libarcsoft_zoom_high_dynamic_range \
    libbeauty_face_interface \
    libbitmlengine \
    libcamera_scene \
    libcamerapostproc \
    libcamlog \
    libcamxcommonutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libceres \
    libceresNM \
    libchifeature2 \
    libchilog \
    libcom.qti.chinodeutils \
    libcom.xiaomi.algomsg \
    libcom.xiaomi.attribute \
    libcom.xiaomi.debug \
    libcom.xiaomi.eventcallback \
    libcom.xiaomi.grallocutils \
    libcom.xiaomi.mawutils \
    libcom.xiaomi.mawutilsold \
    libcom.xiaomi.metadatautils \
    libcom.xiaomi.pluginutils \
    libcommonchiutils \
    libdeflicker \
    libdualcam_optical_zoom_control \
    libdualcam_video_optical_zoom \
    libfastmessage \
    libgf_hal \
    libhdr10plus \
    libhdr_stub \
    libhme \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libjpege \
    libmctfengine_stub \
    libmfGhostDetection \
    libmfec \
    libmiSensorCtrl \
    libmiStereoFactoryRemapBasicLib \
    libmiStereoFactoryRemapLib \
    libmiai_deblur \
    libmiai_portraitsupernight \
    libmialgo_ai_vision \
    libmialgo_aio_seg \
    libmialgo_globalsaliency \
    libmialgo_ie_capture \
    libmialgo_rfs \
    libmialgo_sd \
    libmialgo_snsc \
    libmialgo_utils \
    libmialgo_video_colourkeeping \
    libmialgo_video_seg_depth \
    libmialgoengine \
    libmibokeh_845_video \
    libmiocr \
    libmiphone_capture_bokeh_front \
    libmiphone_preview_bokeh_mono \
    libmis_plugin_dummy \
    libmis_plugin_gme \
    libmis_plugin_his \
    libmis_plugin_morpho \
    libmis_plugin_qisv2 \
    libmis_plugin_qisv3 \
    libmis_plugin_vidhance \
    libmituning_datacenter \
    libmituning_datacenter_base \
    libmituning_utils \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_ubwc \
    libmorpho_video_stabilizer \
    libmpbase \
    libofflinefeatureintf \
    libomp \
    libopencv \
    libopencv3a \
    libopestriping \
    libportrait_repair_qnn \
    libqll \
    libqll10 \
    libqllengine \
    libqsegnet \
    libqshcamera \
    librhytheyecare \
    libsensor_cal@2.0 \
    libsfeShiftExtrapolation \
    libswregistrationalgo \
    libtfestriping \
    libubifocus \
    libvideoBokeh \
    libvideoml \
    libvidhance \
    libvidhance_active_ois \
    libvidhance_face_stabilizer \
    libvidhance_horizon_correction \
    libvidhance_ldc \
    libvidhance_stabilizer \
    libvidhance_super_stabilization \
    libwrapper_dlengine \
    libxmi_hdr_checker \
    libxmi_high_dynamic_range \
    libxmi_slow_motion_mein \
    libxmi_slow_motion_triger \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.xiaomi.hardware.bgservice@1.0-impl \
    odm_lib_rfsa_adsp_libarcsoft_beauty_hvx_skel_so \
    odm_lib_rfsa_adsp_libmialgo_night_align_cdsp_skel_so \
    vendor.qti.camera.provider-service_64
